import assert from "node:assert/strict";
import test from "node:test";
import {
  MemoryMetadataStore,
  MetadataCatalog,
  MetadataEvolution,
  MigrationPlanner,
  createDefaultTypeRegistry,
  defineObjectType,
  diffObjectTypes,
} from "../dist/index.js";

const V1 = defineObjectType({
  id: "example.asset",
  name: "Asset",
  version: 1,
  extensible: true,
  attributes: {
    code: { type: "string", required: true },
    description: { type: "string", nullable: true },
    amount: { type: "decimal" },
  },
  relationships: {
    owner: { target: "example.person", cardinality: "many-to-one" },
  },
  operations: {
    archive: { handler: "asset.archive" },
  },
});

test("classifies additive optional schema evolution as compatible", () => {
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      ...V1.attributes,
      category: { type: "string" },
    },
    operations: {
      ...V1.operations,
      restore: { handler: "asset.restore" },
    },
  });

  const diff = diffObjectTypes(V1, V2);
  assert.equal(diff.impact, "compatible");
  assert.deepEqual(diff.changes.map((entry) => [entry.kind, entry.path, entry.impact]), [
    ["attribute-added", "attributes.category", "compatible"],
    ["operation-added", "operations.restore", "compatible"],
  ]);
});

test("classifies required additions and relationship cardinality changes as breaking", () => {
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      ...V1.attributes,
      serialNumber: { type: "string", required: true },
    },
    relationships: {
      owner: { target: "example.person", cardinality: "many-to-many" },
    },
  });

  const diff = diffObjectTypes(V1, V2);
  assert.equal(diff.impact, "breaking");
  assert.equal(diff.changes.find((entry) => entry.path === "attributes.serialNumber").impact, "breaking");
  assert.equal(diff.changes.find((entry) => entry.path === "relationships.owner").impact, "breaking");
});

test("classifies backfills uniqueness constraints rules and indexes as migrations", () => {
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      code: { type: "string", required: true, unique: true },
      description: { type: "string", nullable: true },
      amount: { type: "decimal", required: true, default: 0 },
      status: { type: "string", required: true, default: "draft" },
    },
    indexes: [
      { name: "ux-asset-code", unique: true, attributes: [{ attribute: "code" }] },
    ],
    rules: [
      { id: "amount-non-negative", type: "amountNonNegative" },
    ],
  });

  const diff = diffObjectTypes(V1, V2);
  assert.equal(diff.impact, "requires-migration");
  assert.equal(diff.changes.find((entry) => entry.path === "attributes.code").impact, "requires-migration");
  assert.equal(diff.changes.find((entry) => entry.path === "attributes.amount").impact, "requires-migration");
  assert.equal(diff.changes.find((entry) => entry.path === "attributes.status").impact, "requires-migration");
  assert.equal(diff.changes.find((entry) => entry.path === "indexes.ux-asset-code").impact, "requires-migration");
  assert.equal(diff.changes.find((entry) => entry.path === "rules.amount-non-negative").impact, "requires-migration");
});

test("migration planner converts semantic changes into ordered portable steps", () => {
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      ...V1.attributes,
      status: { type: "string", required: true, default: "draft" },
    },
    indexes: [{ name: "ix-asset-code", attributes: [{ attribute: "code" }] }],
  });
  const diff = diffObjectTypes(V1, V2);
  const planner = new MigrationPlanner();
  planner.register("index-added", ({ change, ordinal }) => [{
    id: `mysql:${ordinal}:${change.path}`,
    kind: "mysql-ddl",
    path: change.path,
    description: "CREATE INDEX generated by adapter",
    blocking: true,
    changeKind: change.kind,
  }]);

  const plan = planner.plan(diff);
  assert.equal(plan.requiresManualReview, false);
  assert.equal(plan.impact, "requires-migration");
  assert.equal(plan.steps.some((entry) => entry.kind === "backfill-existing-data"), true);
  assert.equal(plan.steps.some((entry) => entry.kind === "rebuild-index"), true);
  assert.equal(plan.steps.some((entry) => entry.kind === "mysql-ddl"), true);
});

test("breaking diffs produce blocking manual-review steps", () => {
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      code: { type: "integer", required: true },
      description: V1.attributes.description,
      amount: V1.attributes.amount,
    },
  });
  const plan = new MigrationPlanner().plan(diffObjectTypes(V1, V2));
  assert.equal(plan.requiresManualReview, true);
  assert.equal(plan.steps.some((entry) => entry.kind === "manual-review" && entry.blocking), true);
});

test("metadata evolution compares persisted catalogue versions", async () => {
  const types = createDefaultTypeRegistry();
  const catalog = new MetadataCatalog(new MemoryMetadataStore(), types);
  const V2 = defineObjectType({
    ...V1,
    version: 2,
    attributes: {
      ...V1.attributes,
      category: { type: "string" },
    },
  });
  await catalog.saveDraft(V1);
  await catalog.saveDraft(V2);

  const evolution = new MetadataEvolution(catalog);
  const diff = await evolution.diff(V1.id, 1, 2);
  assert.equal(diff.impact, "compatible");
  const plan = await evolution.plan(V1.id, 1, 2);
  assert.equal(plan.objectTypeId, V1.id);
  assert.equal(plan.steps.length, 1);
  assert.equal(plan.steps[0].kind, "apply-metadata");
});

test("schema evolution rejects unrelated types and non-forward versions", () => {
  const Other = defineObjectType({ id: "example.other", name: "Other", version: 2, attributes: {} });
  assert.throws(() => diffObjectTypes(V1, Other), /different object types/);
  assert.throws(() => diffObjectTypes(V1, { ...V1, version: 1 }), /higher target version/);
});
